/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Host status and role */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List product entities */
        get: operations["listEntities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket event stream (upgrade)
         * @description Clients connect with `Upgrade: websocket`. Frames are `EventEnvelope` JSON objects.
         *     On a hub, pass `X-Oaa-Node` (or `?node=`) to subscribe to one car's events.
         */
        get: operations["eventsWebSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List fleet nodes (hub only) */
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/pairing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a short-lived pairing code (hub only) */
        post: operations["createPairingCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete pairing from a car node (hub only) */
        post: operations["pairNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/discovered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unpaired cars announcing `_oaa-car._tcp` (hub only, admin) */
        get: operations["listDiscoveredCars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a car for a pairing code (hub only, admin)
         * @description The hub calls the car's `/api/auth/pair/request` with `kind=hub`. The car
         *     shows a 6-digit code on its head unit; the admin types it into
         *     `/api/nodes/invite/{id}/confirm`.
         */
        post: operations["inviteCar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/invite/{inviteId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send the code shown on the car (hub only, admin)
         * @description The hub pre-registers a node token and sends it with the code in the
         *     car's `/api/auth/pair/confirm` (`hub` object). On success the car dials
         *     the node face; the hub keeps the car-issued token and LAN URL.
         */
        post: operations["confirmCarInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/invite/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Forget an open invite (hub only, admin) */
        delete: operations["cancelCarInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Caller identity (car and hub)
         * @description On a car (`role=local`): whether this caller is trusted, its kind and
         *     whether it is the head unit. Hubs answer their session state.
         */
        get: operations["authStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check the head unit session (local only) */
        post: operations["authLocal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pair/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the car to show a pairing code (local only)
         * @description 6-digit code, 3-minute TTL, 5 attempts, one open request per source
         *     address, at most 5 open. The code is shown only on the head unit
         *     (dialog + notification).
         */
        post: operations["carPairRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pair/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm with the code shown on the car (local only)
         * @description Must come from the address that asked. Browsers receive the `oaa_car`
         *     cookie; hubs and tools receive `token` in the body. `kind=hub` requests
         *     must carry `hub`, which the car stores as its hub link.
         */
        post: operations["carPairConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pair/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open pairing requests with their codes (head unit only) */
        get: operations["carPairPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/pair/pending/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Decline a pairing request (head unit only) */
        delete: operations["carPairDecline"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trusted devices (head unit only) */
        get: operations["carClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a trusted device (head unit only)
         * @description Revoking a hub also drops the car's hub link.
         */
        delete: operations["carClientRevoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect / forget a node (hub only) */
        delete: operations["removeNode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Node outbound WebSocket session (hub only)
         * @description Cars connect with `Upgrade: websocket` and authenticate with
         *     `Authorization: Bearer <nodeToken>` (or query `token=`). Frames are
         *     `NodeFrame` JSON. Car→hub: `hello`, `event`, `rpc_result`,
         *     `ota_status`, `log`, `pong`, WebRTC answers/ICE. Hub→car: `rpc`,
         *     `ota_offer`, `public_node` (on connect and on change), `log_subscribe`,
         *     `log_unsubscribe`, `ping`, WebRTC offers/ICE/hangup.
         */
        get: operations["nodeSessionWebSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/artifacts/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download an OTA artifact (hub node face; node token)
         * @description Served on the node face only, with `Authorization: Bearer <nodeToken>`
         *     (or `?token=`). Supports `Range` so cars resume interrupted downloads.
         *     The `ota_offer` frame carries the path to use, which may be the
         *     HA Cloud bridge (`/api/oaa_node/artifacts/{sha256}`). The same path
         *     serves delta patches (`ota_offer.delta.path`), addressed by the
         *     patch's own SHA-256.
         */
        get: operations["downloadArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ota/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stored artifacts, newest first (hub; admin) */
        get: operations["listArtifacts"];
        put?: never;
        /** Upload an APK for OTA (hub; admin) */
        post: operations["uploadArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ota/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rollouts (hub; admin) */
        get: operations["listRollouts"];
        put?: never;
        /**
         * Roll an artifact out to cars (hub; admin)
         * @description Online targets get `ota_offer` immediately; offline ones when they
         *     reconnect. A target becomes `installed` only when the car's `hello`
         *     reports the artifact's APK hash.
         */
        post: operations["createRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ota/rollouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One rollout with per-car state (hub; admin) */
        get: operations["getRollout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live app log stream (WebSocket)
         * @description Text frames, one log line each (recent backlog first). On a car the
         *     contributor `token` is required. On a hub (admins only, car chosen by
         *     `?node=`), the hub sends `log_subscribe {token}` to the car and relays
         *     its `log` frames while at least one viewer is attached. Other
         *     `/debug/*` routes are proxied as regular `rpc` requests.
         */
        get: operations["debugLogStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webrtc/ice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ICE servers for the media plane (human face; session required)
         * @description Hub: returns STUN URLs and, when `OAA_TURN_URLS` + `OAA_TURN_SECRET` are set,
         *     short-lived TURN credentials in the coturn REST format
         *     (`username = <unixExpiry>:<userId>`, `credential = base64(HMAC-SHA1(secret, username))`).
         *     The shared secret never leaves the hub. The hub injects its own
         *     `iceServers` into the offer it relays to the car.
         *
         *     Car (`role=local`, car auth): returns no servers (`iceServers: []`,
         *     `turn: false`); LAN and loopback viewers need none.
         */
        get: operations["getIceServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webrtc/signal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebRTC signaling WebSocket (human face; session required)
         * @description `Upgrade: websocket`. On the hub it is scoped to one car with
         *     `?node=<nodeId>` (or `X-Oaa-Node`). The hub binds this socket to the
         *     node's session by `sessionId` and relays `webrtc_offer` / `webrtc_ice` /
         *     `webrtc_hangup` to the car over the existing node WebSocket;
         *     `webrtc_answer` / `webrtc_ice` / `webrtc_hangup` come back. SDP is never
         *     inspected or persisted.
         *
         *     On the car (`role=local`, car auth) there is no `node` parameter: the
         *     car answers the same frames itself after a `hello {v, role: "local",
         *     online: true}`.
         *
         *     Limits (v1): one hub WebRTC session per node and up to three local
         *     sessions on the car — a newer offer replaces the oldest
         *     (`reason=replaced`); at most 128 relayed ICE candidates per session per
         *     direction; frames ≤ 64 KiB. Any frame whose `v` differs from 1 is
         *     answered with `webrtc_hangup` `reason=version`. Offline node →
         *     `reason=offline`; node without WebRTC support → `reason=unsupported`.
         *
         *     Access (v1): any authenticated hub user may open a session to any
         *     paired node; per-node ACLs are future work.
         */
        get: operations["webrtcSignalWebSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hub join config on a local node (local only) */
        get: operations["getHubConfig"];
        put?: never;
        /** Join or update hub pairing on a local node */
        post: operations["setHubConfig"];
        /** Leave hub (local only) */
        delete: operations["leaveHub"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App update announced by the hub (car)
         * @description The hub sends `ota_available` after every `hello`: its policy (`ask`, `auto`,
         *     `off`) and, when it holds a newer build of this car's package, that build.
         */
        get: operations["getAppUpdate"];
        put?: never;
        /**
         * Install the announced build (car; head unit only)
         * @description Sends `ota_request` to the hub, which answers with `ota_offer` (a delta from
         *     the installed APK when it has or can fetch that build).
         */
        post: operations["installAppUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Status: {
            /** @enum {string} */
            role: "local" | "hub";
            /** @description This host's node id when role=local */
            nodeId?: string | null;
            fleet?: components["schemas"]["Fleet"];
            /** @description False only for the head unit UI (local session); true for paired devices and the hub */
            remote?: boolean;
            webPort?: number;
            integration?: string;
            variant?: string;
            capabilities?: string[];
            /** @description SPA page ids this car serves (`role=local`). Absent on older cars. */
            pages?: string[];
            theme?: string;
            /** @description Present on hubs that relay the media plane (ADR-0003) */
            webrtc?: {
                v?: number;
                turn?: boolean;
            };
        };
        Fleet: {
            nodes?: components["schemas"]["NodeSummary"][];
            /** @description The public node endpoint the hub hands cars (`OAA_PUBLIC_NODE_URL`; all null when unset) */
            publicNode?: {
                url?: string | null;
                /** @description What to type on a car for manual pairing (url plus any bridge prefix) */
                dialUrl?: string | null;
                /** @description Whether the URL leads back to this hub (null until the first check finishes) */
                check?: {
                    ok: boolean;
                    /** @description Why it failed (HTTP status and error, or the connection error) */
                    detail?: string | null;
                    /** Format: int64 */
                    checkedAtMs: number;
                } | null;
            };
            carRelease?: components["schemas"]["CarRelease"];
        };
        /**
         * @description The car app built for this hub's version, fetched from its release folder
         *     (`OAA_CAR_RELEASE_URL`, GitHub Releases by default) and announced to older cars
         *     with `ota_available`. `mode` is the `car_updates` option (`OAA_CAR_UPDATES`).
         */
        CarRelease: {
            /** @enum {string} */
            mode: "ask" | "auto" | "off";
            /** @enum {string} */
            state: "ready" | "fetching" | "unavailable" | "off";
            versionName?: string | null;
            /** Format: int64 */
            versionCode?: number | null;
            /** @description Release folder holding `car-apk.json` and the APK */
            url: string;
            /** @description Last fetch failure while no release is stored */
            error?: string | null;
        };
        /** @description The hub's app update for this car, and the progress of one in flight */
        AppUpdate: {
            paired: boolean;
            online: boolean;
            /** @description Installed build */
            versionName?: string | null;
            /** Format: int64 */
            versionCode?: number | null;
            /**
             * @description The hub's policy from `ota_available`; null until a hub that announces updates connects
             * @enum {string|null}
             */
            mode?: "ask" | "auto" | "off" | null;
            available?: {
                versionName?: string | null;
                /** Format: int64 */
                versionCode?: number;
                /**
                 * Format: int64
                 * @description Full APK bytes
                 */
                size?: number;
                /**
                 * Format: int64
                 * @description Delta patch bytes, once the hub has built one from the installed APK
                 */
                downloadSize?: number | null;
            } | null;
            /** @description `pending` after `POST`, then the `ota_status` states */
            state?: string | null;
            progress?: number | null;
            error?: string | null;
            /** @description `POST` only */
            ok?: boolean;
        };
        NodeSummary: {
            id: string;
            name: string;
            online: boolean;
            integration?: string | null;
            /** Format: int64 */
            lastSeenMs?: number | null;
            /** @description Build reported in the car's last `hello` */
            app?: components["schemas"]["AppInfo"] | null;
            /** @description Latest rollout state for this car */
            ota?: components["schemas"]["OtaTargetState"] | null;
            /**
             * @description Hub URL the connected car dialed, from its `hello`; null while offline or for cars before 0.1.1
             * @enum {string|null}
             */
            via?: "local" | "public" | null;
        };
        PairingOffer: {
            /** @description Short numeric/alphanumeric code shown in hub UI */
            code: string;
            /** Format: int64 */
            expiresAtMs: number;
        };
        PairRequest: {
            code: string;
            /** @description Stable id chosen by the car (e.g. android_id hash) */
            nodeId: string;
            name: string;
            integration?: string;
        };
        PairResponse: {
            ok: boolean;
            nodeId: string;
            /** @description Long-lived bearer token for /api/nodes/session */
            token: string;
            /** @description Node-face base URL the car should dial (tunnel / HA Cloud) */
            publicNodeUrl?: string | null;
            /** @description Session path on publicNodeUrl (default `/api/nodes/session`) */
            sessionPath?: string;
            /** @description Stable hub id; the car lists the hub under trusted devices */
            hubId?: string;
            hubName?: string;
        };
        DiscoveredCar: {
            id: string;
            name?: string;
            integration?: string | null;
            version?: string | null;
            host: string;
            port: number;
            /** Format: int64 */
            seenAtMs?: number;
        };
        /** @description A discovered `nodeId`, or a `host` (optionally `host:port`) */
        CarInviteRequest: {
            nodeId?: string;
            host?: string;
            /** @default 8787 */
            port: number;
        };
        CarInvite: {
            ok: boolean;
            inviteId: string;
            nodeId: string;
            name?: string;
            /** Format: int64 */
            expiresAtMs?: number;
        };
        CarAuthStatus: {
            /** @enum {string} */
            role?: "local" | "hub";
            authenticated?: boolean;
            /** @enum {string|null} */
            kind?: "hu" | "browser" | "hub" | "tool" | "internal" | null;
            headUnit?: boolean;
            loopback?: boolean;
            setupRequired?: boolean;
        };
        CarPairRequest: {
            /**
             * @default browser
             * @enum {string}
             */
            kind: "browser" | "hub" | "tool";
            /** @description Shown on the head unit next to the code */
            name?: string;
            /** @description Stable hub id (`kind=hub`) */
            hubId?: string;
        };
        CarPairRequestResponse: {
            ok?: boolean;
            requestId?: string;
            /** Format: int64 */
            expiresAtMs?: number;
            nodeId?: string | null;
            name?: string | null;
            integration?: string;
        };
        CarPairConfirm: {
            requestId: string;
            code: string;
            /** @description Hub link (`kind=hub` only) */
            hub?: {
                hubId?: string;
                hubName?: string;
                /** @description Node token the hub pre-registered for this car */
                nodeToken?: string;
                /** @description Node face port; the car dials the hub's source address on it first */
                nodePort?: number;
                /** @description Published node-face URLs (tunnel / HA Cloud), tried next */
                nodeUrls?: string[];
                sessionPath?: string;
            };
        };
        CarPairPending: {
            id?: string;
            kind?: string;
            name?: string;
            code?: string;
            source?: string;
            /** Format: int64 */
            expiresAtMs?: number;
        };
        CarClient: {
            id?: string;
            /** @enum {string} */
            kind?: "browser" | "hub" | "tool";
            name?: string;
            /** Format: int64 */
            createdAtMs?: number;
            /** Format: int64 */
            lastSeenMs?: number | null;
            hubId?: string | null;
        };
        HubJoinConfig: {
            enabled?: boolean;
            hubUrl?: string;
            hubId?: string | null;
            hubName?: string | null;
            /** @description The node-face URL the session is using or trying (localNodeUrl or publicNodeUrl). */
            nodeUrl?: string | null;
            /** @description Node face on the hub's LAN, used whenever the hub answers there. */
            localNodeUrl?: string | null;
            /** @description Node face from anywhere (Nabu Casa or a tunnel), used when the local one is unreachable. */
            publicNodeUrl?: string | null;
            /** @enum {string|null} */
            via?: "local" | "public" | null;
            nodeId?: string | null;
            paired?: boolean;
            online?: boolean;
            lastError?: string | null;
        };
        HubJoinRequest: {
            /** @description Base URL of the hub (e.g. http://192.168.1.10:8787) */
            hubUrl: string;
            code: string;
            /** @description Optional display name override */
            name?: string;
        };
        Entity: {
            /**
             * @description Stable catalog id (`climate.cabin`, `sensor.soc`, …)
             * @example climate.cabin
             */
            id: string;
            /**
             * @description EntityType id (climate, sensor, switch, …)
             * @example climate
             */
            domain: string;
            state?: string | null;
            /** @description Current value (product field; often same as state) */
            value?: string | null;
            friendlyName?: string;
            label?: string;
            available?: boolean;
            /** @enum {string} */
            status?: "ok" | "cached" | "denied" | "unavailable" | "failed";
            deviceClass?: string | null;
            unitOfMeasurement?: string | null;
            attributes?: {
                [key: string]: unknown;
            };
            /** @description Nav section id (home, energy, controls, …) */
            group?: string;
            composite?: boolean;
            /**
             * @description Live-update policy for WebSocket clients
             * @enum {string}
             */
            update?: "entity" | "catalog";
        };
        /** @description Viewer event on `/api/events`; fields besides `t` depend on the type. */
        EventEnvelope: {
            /**
             * @description `entity` — atomic value patch (`id`, `value`, `status`);
             *     `catalog` — reload /api/entities; `telemetry` — session telemetry snapshot
             *     (at most once per second); `dvr` — DVR summary (mode, storage, usage), sent
             *     only when it changes
             * @enum {string}
             */
            t: "hello" | "ping" | "telemetry" | "entity" | "catalog" | "dvr";
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Frame on `/api/nodes/session`. Payload shapes: `hello` → `NodeHello`,
         *     `event` → `EventEnvelope`, `rpc` → `RpcRequest`, `rpc_result` →
         *     `RpcResult`, `ota_offer` → `OtaOffer`, `ota_status` → `OtaStatus`,
         *     `log_subscribe` → `{v, token?}`, `log` → `{line}`, `public_node` →
         *     `{v, publicNodeUrl?, sessionPath}`; WebRTC frames are
         *     `WebRtcSignal`. `ping` / `pong` / `log_unsubscribe` carry no payload.
         */
        NodeFrame: {
            /** @enum {string} */
            type: "hello" | "event" | "ping" | "pong" | "rpc" | "rpc_result" | "ota_offer" | "ota_status" | "public_node" | "log_subscribe" | "log_unsubscribe" | "log" | "webrtc_offer" | "webrtc_answer" | "webrtc_ice" | "webrtc_hangup";
            payload?: {
                [key: string]: unknown;
            };
        };
        NodeHello: {
            /** @enum {integer} */
            v: 1;
            nodeId: string;
            name?: string;
            integration?: string;
            /** @description Protocol / app version (0.1.0) */
            version?: string;
            app?: components["schemas"]["AppInfo"];
            /**
             * @description Which of its hub URLs the car dialed for this session
             * @enum {string}
             */
            via?: "local" | "public";
        };
        AppInfo: {
            package?: string;
            versionName?: string;
            /** Format: int64 */
            versionCode?: number;
            /** @description Hash of the installed APK; the hub's source of truth for `installed` */
            apkSha256?: string | null;
        };
        /**
         * @description Hub→car proxied HTTP. Textual bodies (text/*, JSON, XML, JS, form) use
         *     `body`; anything else `bodyB64`. Bodies over 2.5 MiB are refused (413).
         */
        RpcRequest: {
            id: string;
            /** @enum {string} */
            method: "GET" | "POST" | "PUT" | "DELETE";
            path: string;
            /** @description Raw query string without `?` */
            query?: string;
            contentType?: string;
            body?: string;
            /** Format: byte */
            bodyB64?: string;
        };
        RpcResult: {
            id: string;
            status: number;
            contentType?: string;
            contentDisposition?: string;
            body?: string;
            /** Format: byte */
            bodyB64?: string;
        };
        OtaOffer: {
            /** @enum {integer} */
            v: 1;
            rolloutId: string;
            sha256: string;
            /** Format: int64 */
            size?: number;
            package?: string;
            versionName?: string | null;
            /** Format: int64 */
            versionCode?: number | null;
            /** @description Download path relative to the car's node URL */
            path: string;
            /**
             * @description Present when the car's reported APK (`hello.app.apkSha256`) is a stored
             *     artifact. The car rebuilds the target from its installed APK plus this
             *     OADP patch, checks the result against `sha256`, and falls back to `path`
             *     on any failure.
             */
            delta?: {
                /** @description SHA-256 of the installed APK the patch applies to */
                from: string;
                /** @description SHA-256 of the patch file */
                sha256: string;
                /** Format: int64 */
                size: number;
                /** @description Patch download path relative to the car's node URL */
                path: string;
            };
        };
        /** @description Car progress report. `installed` is ignored here; only `hello` confirms it. */
        OtaStatus: {
            /** @enum {integer} */
            v: 1;
            rolloutId: string;
            state: components["schemas"]["OtaState"];
            progress?: number;
            error?: string;
        };
        /** @enum {string} */
        OtaState: "pending" | "offered" | "downloading" | "verifying" | "installing" | "pending_user" | "installed" | "failed";
        OtaTargetState: {
            rolloutId?: string;
            sha256?: string;
            state?: components["schemas"]["OtaState"];
            progress?: number | null;
            error?: string | null;
            /** Format: int64 */
            updatedAtMs?: number;
        };
        Artifact: {
            sha256: string;
            /** Format: int64 */
            size: number;
            packageName: string;
            versionName?: string | null;
            /** Format: int64 */
            versionCode?: number | null;
            /** Format: int64 */
            uploadedAtMs?: number;
        };
        Rollout: {
            id: string;
            sha256: string;
            /** Format: int64 */
            createdAtMs?: number;
            done: boolean;
            targets: {
                [key: string]: {
                    state?: components["schemas"]["OtaState"];
                    progress?: number | null;
                    error?: string | null;
                    /** Format: int64 */
                    updatedAtMs?: number;
                };
            };
        };
        IceConfig: {
            /** @enum {integer} */
            v: 1;
            iceServers: {
                urls: string[];
                username?: string;
                credential?: string;
            }[];
            /** @description Lifetime of the TURN credential */
            ttlSec?: number;
            /** @description True when TURN relay credentials are included */
            turn?: boolean;
        };
        /**
         * @description Signaling envelope on `/api/webrtc/signal` and on the node session.
         *     Directions: `webrtc_offer` viewer→car; `webrtc_answer` car→viewer;
         *     `webrtc_ice` and `webrtc_hangup` both ways. The viewer creates the
         *     offer (up to four recvonly H.264 video m-lines + the `oaa-media` data
         *     channel); the car fills one m-line per camera, each track in the
         *     MediaStream `oaa-cam-<role>`, and leaves the rest inactive.
         */
        WebRtcSignal: {
            /** @enum {string} */
            type: "webrtc_offer" | "webrtc_answer" | "webrtc_ice" | "webrtc_hangup";
            payload: {
                /** @enum {integer} */
                v: 1;
                sessionId: string;
                /** @description offer / answer only */
                sdp?: string;
                /** @description answer only — negotiated codecs (e.g. `H264`) */
                codecs?: string[];
                /** @description answer only — camera roles with a video track, in m-line order */
                tracks?: string[];
                candidate?: string;
                sdpMid?: string | null;
                sdpMLineIndex?: number | null;
                /** @description Added by the hub to the offer it forwards to the car */
                iceServers?: Record<string, never>[];
                /**
                 * @description hangup only
                 * @enum {string}
                 */
                reason?: "version" | "busy" | "replaced" | "offline" | "unsupported" | "bye" | "invalid" | "error";
            };
        };
        /**
         * @description First message the car sends on the `oaa-media` data channel (reliable,
         *     ordered). The viewer must only use features listed here.
         *
         *     Viewer→car JSON messages (all with `v: 1`; transfers carry a numeric `reqId`):
         *     `playback_open {reqId, name, offsetMs?}` or `playback_open {reqId, atMs, role}`
         *     (one camera's recording; `atMs` resolves the file covering that wall time),
         *     `playback_seek {reqId, offsetMs? | atMs + role?}`, `playback_close {reqId}`,
         *     `download_open {reqId, name}` (basename only — `/`, `\`, `..` rejected),
         *     `cut_request {reqId, role, fromMs, toMs}` (one camera, ≤ `maxCutMs`; the
         *     car re-encodes the range with the time burned in), `transfer_cancel {reqId}`.
         *     Without `reqId`: `live_select {roles?}` (cameras to send; omitted = all),
         *     `live_pause` / `live_resume` (stop/start sending live video frames, e.g.
         *     while the viewer tab is hidden — resume starts on a key frame),
         *     `clock_sync {t0}` (viewer clock ms).
         *
         *     Car→viewer JSON: `media_meta {reqId, kind, name?, mime, codec?, size?,
         *     offsetMs?, atMs?, durationMs?, role?, group?, fileStartUtcMs?,
         *     segStartUtcMs?, segEndUtcMs?}` precedes the bytes of each transfer (and
         *     each playback restart after a seek); `media_progress {reqId, doneMs,
         *     totalMs}` while a cut is being encoded; `media_error {reqId, error}`;
         *     `live_tracks {roles, streaming}` when the set of sending cameras
         *     changes; `clock {t0, carUtcMs}` answering `clock_sync`. Bytes arrive as
         *     binary `MediaChunk` frames.
         *
         *     Live RTP timestamps are the frame's capture time: `captureUtcMs × 90`
         *     mod 2^32. Viewers unwrap them against the car clock to draw the time.
         *
         *     Playback container contract: always fragmented MP4 (init + moof/mdat)
         *     for Media Source Extensions, mime `video/mp4; codecs="avc1.PPCCLL"`
         *     taken from the SPS. Downloads and cuts are progressive MP4 files.
         *     At most `maxTransfers` concurrent transfers per session (enough for
         *     four playback streams plus downloads); chunks ≤ `chunkMaxBytes`;
         *     senders respect `bufferedAmount` backpressure.
         */
        DataChannelHello: {
            /** @enum {string} */
            type: "dc_hello";
            /** @enum {integer} */
            v: 1;
            sessionId: string;
            features: ("live" | "playback" | "download" | "cut")[];
            /** @description Camera roles on this car, e.g. `front`, `right`, `rear`, `left` */
            cameras?: string[];
            /** @description Camera roles with a live track in this session */
            tracks?: string[];
            /**
             * Format: int64
             * @description Car wall clock when the hello was sent
             */
            carUtcMs?: number;
            /**
             * @description Longest `cut_request` range
             * @example 600000
             */
            maxCutMs?: number;
            /** @enum {string} */
            playbackContainer?: "fmp4";
            /** @example 262144 */
            chunkMaxBytes?: number;
            /** @example 6 */
            maxTransfers?: number;
        };
        /**
         * Format: binary
         * @description Binary data-channel frame, big-endian:
         *     `u8 type (1=chunk) | u32 reqId | u32 seq | u8 flags | payload`.
         *     Flags: `0x01` eof (last chunk of the transfer), `0x02` init (fMP4
         *     initialization segment). `seq` restarts at 0 for each transfer or
         *     playback restart. Payload ≤ `chunkMaxBytes`.
         */
        MediaChunk: string;
    };
    responses: never;
    parameters: {
        /** @description On hub hosts, select which paired car to address (else `?node=`, else the `oaa_node` cookie) */
        OaaNodeHeader: string;
        Sha256Path: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: {
                /** @description On hub hosts, select which paired car to address (else `?node=`, else the `oaa_node` cookie) */
                "X-Oaa-Node"?: components["parameters"]["OaaNodeHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    listEntities: {
        parameters: {
            query?: {
                /** @description When `1`, include entities marked hidden by the user */
                includeHidden?: "1";
            };
            header?: {
                /** @description On hub hosts, select which paired car to address (else `?node=`, else the `oaa_node` cookie) */
                "X-Oaa-Node"?: components["parameters"]["OaaNodeHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity catalog snapshot (JSON array of Entity maps) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"][];
                };
            };
        };
    };
    eventsWebSocket: {
        parameters: {
            query?: {
                /** @description Alternate to X-Oaa-Node for WebSocket clients */
                node?: string;
            };
            header?: {
                /** @description On hub hosts, select which paired car to address (else `?node=`, else the `oaa_node` cookie) */
                "X-Oaa-Node"?: components["parameters"]["OaaNodeHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols (WebSocket) */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Documentation stub — live clients must use WebSocket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fleet snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fleet"];
                };
            };
            /** @description Not a hub (`role` is local) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createPairingCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pairing offer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingOffer"];
                };
            };
        };
    };
    pairNode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Paired node credentials */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
            /** @description Invalid or expired code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDiscoveredCars: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cars seen by mDNS that are not paired to this hub */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cars?: components["schemas"]["DiscoveredCar"][];
                    };
                };
            };
        };
    };
    inviteCar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarInviteRequest"];
            };
        };
        responses: {
            /** @description Invite open on the car */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarInvite"];
                };
            };
            /** @description The car already has an open request from this hub */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Car unreachable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmCarInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Paired */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        node?: components["schemas"]["NodeSummary"];
                    };
                };
            };
            /** @description Wrong code */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invite or car request expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelCarInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auth state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarAuthStatus"];
                };
            };
        };
    };
    authLocal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller is the head unit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the head unit */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    carPairRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarPairRequest"];
            };
        };
        responses: {
            /** @description Request open */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarPairRequestResponse"];
                };
            };
            /** @description Too many open requests, or one already open from this address */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    carPairConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarPairConfirm"];
            };
        };
        responses: {
            /** @description Paired */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        /** @description Car-issued bearer token (hub and tool only) */
                        token?: string;
                        clientId?: string;
                        nodeId?: string;
                    };
                };
            };
            /** @description Wrong code, or confirm from another address */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown or expired request */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    carPairPending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pending?: components["schemas"]["CarPairPending"][];
                    };
                };
            };
        };
    };
    carPairDecline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Declined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    carClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paired browsers, hubs and tools */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        clients?: components["schemas"]["CarClient"][];
                    };
                };
            };
        };
    };
    carClientRevoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown client */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    nodeSessionWebSocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: components["parameters"]["Sha256Path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description APK bytes, or an OADP patch for a delta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.android.package-archive": string;
                    "application/vnd.oaa.apk-delta": string;
                };
            };
            /** @description Partial content for a `Range` request */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid node token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown artifact */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifacts (the hub keeps the last 5) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        artifacts?: components["schemas"]["Artifact"][];
                    };
                };
            };
        };
    };
    uploadArtifact: {
        parameters: {
            query?: never;
            header: {
                "X-Oaa-Package": string;
                "X-Oaa-Version-Name"?: string;
                "X-Oaa-Version-Code"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/vnd.android.package-archive": string;
            };
        };
        responses: {
            /** @description Stored (content-addressed; re-uploads are idempotent) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        artifact?: components["schemas"]["Artifact"];
                    };
                };
            };
            /** @description Over 256 MiB */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRollouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollouts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rollouts?: components["schemas"]["Rollout"][];
                    };
                };
            };
        };
    };
    createRollout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Artifact sha256 */
                    artifact: string;
                    nodes?: string[];
                    /** @description Target every paired car instead of `nodes` */
                    all?: boolean;
                };
            };
        };
        responses: {
            /** @description Rollout created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        rollout?: components["schemas"]["Rollout"];
                    };
                };
            };
            /** @description Missing targets or unknown nodes */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown artifact */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRollout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rollout"];
                };
            };
            /** @description Unknown rollout */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    debugLogStream: {
        parameters: {
            query?: {
                token?: string;
                node?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getIceServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ICE configuration for RTCPeerConnection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IceConfig"];
                };
            };
            /** @description Hub session required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    webrtcSignalWebSocket: {
        parameters: {
            query?: {
                /** @description Hub only (required there) */
                node?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols. Frames are `WebRtcSignal` JSON. */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHubConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current hub pairing state on this car */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubJoinConfig"];
                };
            };
        };
    };
    setHubConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HubJoinRequest"];
            };
        };
        responses: {
            /** @description Updated config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubJoinConfig"];
                };
            };
        };
    };
    leaveHub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    getAppUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Update state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppUpdate"];
                };
            };
        };
    };
    installAppUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requested */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppUpdate"];
                };
            };
            /** @description Not the head unit */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No update announced, or the hub is offline */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppUpdate"];
                };
            };
        };
    };
}
